openapi: 3.0.1
info:
  title: Petstore API
  description: A sample API for a pet store
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
paths:
  /pets:
    get:
      summary: Returns a list of pets
      description: Returns a list of pets that the user owns
      operationId: listPets
      responses:
        '200':
          description: A list of pets
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: Fluffy
                    species:
                      type: string
                      example: Dog
        '400':
          description: Invalid input
  /pets/{petId}:
    get:
      summary: Get a pet by ID
      description: Retrieve a pet's details using its ID
      operationId: getPetById
      parameters:
        - in: path
          name: petId
          required: true
          description: The ID of the pet to retrieve
          schema:
            type: integer
      responses:
        '200':
          description: Pet found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  species:
                    type: string
        '404':
          description: Pet not found
